/**
 * System of record for the Commercial Decision Methodology.
 *
 * Rule: nothing shown to a human exists without provenance. Every metric, constraint, exposure,
 * intervention, decision, registration, measurement and learning record carries evidence ids that
 * resolve to Observations, and every Observation carries a Source, a timestamp and a status.
 *
 * Status vocabulary (never blurred):
 *  - VERIFIED      : read directly from a system of record (PMS, GA4, ledger). None in the simulation.
 *  - SIMULATED     : generated by the simulated-property model for the proof-of-concept.
 *  - MODELLED      : computed from other values by a declared formula and assumptions.
 *  - BENCHMARK     : an external reference value; a placeholder until a documented source replaces it.
 *  - EXPERIMENTAL  : a hypothesis to be tested.
 */

export type Status = "VERIFIED" | "SIMULATED" | "MODELLED" | "BENCHMARK" | "EXPERIMENTAL";
export type Confidence = number; // 0..1, always stated with how it was set

export interface Source {
  readonly id: string;               // "SRC-SIM-PMS"
  readonly name: string;             // "Simulated PMS export"
  readonly kind: "simulation" | "system" | "benchmark" | "derived";
  readonly note: string;
}

export interface Observation {
  readonly id: string;               // "OBS-019"
  readonly metric: string;           // "sessions.mobile"
  readonly value: number;
  readonly unit: string;             // "sessions/year", "GBP", "ratio", "weeks"
  readonly period: string;           // "2025-W01..2026-W52", "annual"
  readonly source: string;           // Source.id
  readonly timestamp: string;        // ISO-8601, when observed / generated
  readonly transformation: string;   // "raw" | formula text
  readonly assumptions: readonly string[];
  readonly confidence: Confidence;
  readonly status: Status;
  readonly evidence: readonly string[]; // upstream Observation ids (empty for raw)
}

export interface Metric extends Observation {
  readonly formula: string;          // human-readable derivation
}

export interface Range { readonly low: number; readonly high: number; }

export type ConstraintKind = "DEMAND" | "CONVERSION" | "CAPACITY" | "OPERATIONAL" | "ECONOMIC" | "RETENTION";
export type InterventionStatus = "FUNDED" | "BLOCKED" | "INVESTIGATE" | "REJECTED" | "DEFERRED";

export interface Constraint {
  readonly id: string;               // "C-001"
  readonly kind: ConstraintKind;
  readonly factor: string;           // "conversion"
  readonly name: string;
  readonly metric: string;
  readonly observed: number;
  readonly benchmark: number;
  readonly attainment: number;       // observed / benchmark, capped at 1
  readonly gapGbp: Range;            // annual value lost to this factor, before dedup
  readonly confidence: Confidence;
  readonly evidence: readonly string[];
  readonly status: Status;
  readonly formula: string;
  readonly assumptions: readonly string[];
  readonly dependsOn: readonly string[]; // constraint ids upstream in the causal chain
}

export interface Diagnosis {
  readonly potentialGbp: number;     // under benchmark assumptions
  readonly attainableGbp: number;    // given declared property limits
  readonly actualGbp: number;
  readonly constraints: readonly Constraint[];
  readonly totalAddressableGbp: number;   // naive sum of midpoints
  readonly deduplicatedGbp: Range;        // after overlap removal
  readonly dedupMethod: string;
  readonly binding: string | null;        // constraint id that limits the system now
  readonly bindingWhy: string;
  readonly evidence: readonly string[];
  readonly computedAt: string;
}

export interface Exposure {
  readonly id: string;               // "E-001"
  readonly name: string;
  readonly horizonMonths: number;
  readonly probability: number;      // MODELLED ASSUMPTION unless status says otherwise
  readonly probabilityBasis: string;
  readonly valueAtRiskGbp: Range;
  readonly drivers: readonly string[];
  readonly mitigation: readonly string[];
  readonly uncertainty: string;
  readonly evidence: readonly string[];
  readonly status: Status;
  readonly formula: string;
}

export interface Intervention {
  readonly id: string;               // "I-001"
  readonly name: string;
  readonly actsOn: string;           // factor id
  readonly addresses: readonly string[]; // constraint ids
  readonly costGbp: number;          // ESTIMATED INTERVENTION BUDGET (layer 2): the economic budget the intervention needs — not a provider quote, not the partnership fee, not authorised spend
  readonly effectIfWorksGbp: Range;  // annual
  readonly confidence: Confidence;   // probability it works as intended (declared, then calibrated)
  readonly confidenceBasis: string;
  readonly risk: "Low" | "Medium" | "High";
  readonly reversibility: "High" | "Medium" | "Low";
  readonly timeToImpactWeeks: number;
  readonly mustFollow: readonly string[]; // intervention ids
  readonly informationOption: { readonly name: string; readonly costGbp: number; readonly quality: number } | null;
  readonly evidence: readonly string[];
  readonly calibration: { readonly factor: number; readonly cycles: number } | null;
}

export interface VoiResult {
  readonly interventionId: string;
  readonly expectedValueGbp: number;
  readonly evpiGbp: number;
  readonly evsiGbp: number;
  readonly informationCostGbp: number;
  readonly decision: "PROCEED" | "COLLECT_MORE_INFORMATION" | "DO_NOT_ACT";
  readonly reason: string;
}

export interface AssayVerdict {
  readonly ownerPlanValueGbp: number;
  readonly informedPlanValueGbp: number;
  readonly valueOfDiagnosisGbp: number;
  readonly thesisPriceGbp: number;
  readonly ratio: number;
  readonly verdict: "PROCEED" | "MORE_INFORMATION_REQUIRED" | "DECLINE";
  readonly reason: string;
}

export interface AllocationLine {
  readonly interventionId: string;
  readonly allocatedGbp: number;
  readonly riskAdjustedValueGbp: number;
  readonly expectedValueGbp: number;
  readonly funded: boolean;
  readonly status: InterventionStatus;
  readonly blockedBy: readonly string[]; // reasons
  readonly requiredCondition: string | null;
  readonly qualityFactor: number;        // data-quality multiplier applied to confidence (1 = full quality)
}

export interface Allocation {
  readonly budgetGbp: number;
  readonly reserveGbp: number;
  readonly lines: readonly AllocationLine[];
  readonly allocatedGbp: number;
  readonly formula: string;
}

export interface ChangeCondition { readonly metric: string; readonly operator: ">" | "<" | ">=" | "<="; readonly threshold: number; readonly why: string; readonly interventionId: string | null; readonly fromStatus: string | null; readonly toStatus: string | null; readonly basis: "threshold_search" | "break_even" | "benchmark" | "condition"; }

export interface Decision {
  readonly id: string;               // "D-001"
  readonly timestamp: string;
  readonly question: string;
  readonly alternatives: readonly string[];
  readonly selected: readonly string[];
  readonly rejected: readonly { readonly id: string; readonly reasons: readonly string[] }[];
  readonly constraints: readonly string[];
  readonly evidence: readonly string[];
  readonly assumptions: readonly string[];
  readonly expectedValueGbp: number;
  readonly confidence: Confidence;
  readonly confidenceBasis: string;
  readonly wouldChangeIf: readonly ChangeCondition[];
  readonly governance: { readonly level: 0 | 1 | 2 | 3 | 4; readonly reason: string };
}

export interface MeasurementPlan {
  readonly id: string;               // "MP-001"
  readonly version: number;
  readonly supersedes: string | null;
  readonly registeredAt: string;
  readonly interventionIds: readonly string[];
  readonly hypotheses: readonly string[];
  readonly primaryMetric: string;
  readonly secondaryMetrics: readonly string[];
  readonly baseline: string;
  readonly expectedGbp: Range;       // P10..P90 implied by our own assumptions
  readonly expectedPointGbp: number;
  readonly windowWeeks: number;
  readonly counterfactualMethod: string;
  readonly successRule: string;
  readonly stoppingRule: string;
  readonly sha256: string;
}

export interface MeasurementResult {
  readonly planId: string;
  readonly planIntact: boolean;
  readonly method: string;
  readonly methodWhy: string;
  readonly observedGbp: number;
  readonly counterfactualGbp: number;
  readonly incrementalGbp: Range;    // 90 % interval
  readonly incrementalPointGbp: number;
  readonly effectPct: number;
  readonly sePct: number;
  readonly pPositive: number;
  readonly placebo: { readonly passed: boolean; readonly rank: number; readonly of: number; readonly note: string };
  readonly preFitRmspe: number;
  readonly status: "ESTABLISHED" | "PROVISIONAL" | "INCONCLUSIVE";
  readonly planStatus: "VALIDATED" | "PARTIALLY_VALIDATED" | "NOT_VALIDATED";
  readonly measuredAt: string;
}

export interface LearningRecord {
  readonly id: string;               // "LR-001"
  readonly timestamp: string;
  readonly propertyId: string;
  readonly interventionTypes: readonly string[];
  readonly context: Record<string, number>;
  readonly expectedGbp: number;
  readonly observedGbp: number;
  readonly error: number;            // (observed - expected) / expected
  readonly measurementStatus: MeasurementResult["status"];
  readonly calibrationApplied: boolean;
  readonly calibrationNote: string;
}

/** Intervention control record (challenge §16): everything a human needs to own, approve, run and judge an intervention. */
export interface InterventionRecord {
  readonly id: string; readonly name: string; readonly objective: string; readonly problem: string; readonly constraint: readonly string[]; readonly constraintKind: ConstraintKind | null;
  readonly owner: string; readonly team: string;
  readonly dependency: readonly string[]; readonly dependencyStatus: "NONE" | "SATISFIED" | "UNRESOLVED" | "RESOLVED_BY_MEASUREMENT";
  readonly capitalGbp: number; readonly expectedImpactGbp: Range; readonly expectedValueGbp: number;
  readonly risk: "Low" | "Medium" | "High"; readonly reversibility: "High" | "Medium" | "Low"; readonly confidence: number; readonly confidenceBasis: string;
  readonly measurementPlanId: string | null; readonly successThreshold: string;
  readonly decisionStatus: InterventionStatus; readonly blockedBy: readonly string[]; readonly whatWouldUnblock: string | null;
  readonly approvalLevel: 0 | 1 | 2 | 3 | 4; readonly approvalTier: string;
  readonly startDate: string | null; readonly endDate: string | null;
  readonly outcome: { readonly status: string; readonly incrementalGbp: number; readonly planStatus: string } | null;
  readonly forecastError: number | null; readonly learning: string | null;
  readonly history: string;            // memory recall statement
  readonly evidence: readonly string[];
  readonly budget: import("./economics.js").InterventionBudget;       // layer 2: a decision of its own, never the partnership
  readonly package: import("./economics.js").DecisionPackage;         // what the client receives
}

export type EngineState =
  | "IDLE" | "OBSERVING" | "DIAGNOSING" | "INVESTIGATING" | "COMPARING" | "DECIDING"
  | "BLOCKING" | "MEASURING" | "LEARNING" | "ALERT";

export interface EngineEvent {
  readonly seq: number;
  readonly at: string;               // ISO-8601, captured when emitted
  readonly type: string;             // "DIAGNOSIS_STARTED" ...
  readonly state: EngineState;
  readonly detail: string;
  readonly refs: readonly string[];  // ids of records this event concerns
}
