import { getRun, listRuns } from "@/lib/engine/store";
export const dynamic = "force-dynamic";
const gbp = (x: number) => `£${Math.round(x).toLocaleString("en-GB")}`;
const esc = (s: string) => s.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]!);

/** GET /api/engine/report/[id] — the demo report, generated from the run's records (HTML, printable). */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const run = id === "latest" ? listRuns().at(-1) : getRun(id);
  if (!run) return new Response("no such run", { status: 404 });
  const r = run.result, d = r.diagnosis, m = r.measurement;
  const row = (k: string, v: string) => `<tr><th>${esc(k)}</th><td>${v}</td></tr>`;
  const html = `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><title>Anesis — Decision report ${run.id}</title>
<style>body{font-family:Georgia,serif;color:#122A1D;background:#FBF8F1;max-width:52rem;margin:2rem auto;padding:0 1.5rem;line-height:1.5}h1,h2{font-weight:400}h1{font-size:2rem}h2{margin-top:2.2rem;border-bottom:1px solid #CBAE79;padding-bottom:.3rem}table{border-collapse:collapse;width:100%;font-size:.92rem}th,td{text-align:left;vertical-align:top;padding:.35rem .5rem;border-bottom:1px solid #E4D8C2}th{width:16rem;font-weight:400;color:#8F6F38}.tag{display:inline-block;font-size:.7rem;letter-spacing:.2em;text-transform:uppercase;color:#8F6F38;border:1px solid #CBAE79;padding:.15rem .5rem;border-radius:999px}.small{font-size:.8rem;color:#2A5A41}</style></head><body>
<p class="tag">Simulated property data · proof-of-concept</p>
<h1>Anesis — Commercial decision report</h1>
<p class="small">Run ${run.id} · ${esc(run.createdAt)} · seed ${run.input.seed} · budget ${gbp(run.input.budgetGbp)} · engine time ${run.durationMs} ms · memory records used ${run.input.memoryUsed}</p>
<h2>1. What was observed</h2><table>${row("Property", esc(r.property.spec.name) + " — " + r.property.spec.rooms + " rooms, SIMULATED")}${row("Observations", r.property.observations.length + " with source, timestamp, transformation, status")}${row("Consistency", r.consistency.length ? esc(r.consistency.join("; ")) : "all identities hold")}</table>
<h2>2. Diagnosis</h2><table>${row("Actual room revenue", gbp(d.actualGbp))}${row("Attainable", gbp(d.attainableGbp))}${row("Potential (benchmark assumptions)", gbp(d.potentialGbp))}${row("Total addressable (naive)", gbp(d.totalAddressableGbp))}${row("Deduplicated", `${gbp(d.deduplicatedGbp.low)} – ${gbp(d.deduplicatedGbp.high)}`)}${row("Deduplication rule", esc(d.dedupMethod))}${row("Limiting constraint", esc(d.binding ?? "none") + " — " + esc(d.bindingWhy))}</table>
<table>${d.constraints.map((c) => row(c.id + " " + c.factor, `${esc(c.name)}<br><span class="small">observed ${c.observed} · benchmark ${c.benchmark} · attainment ${(c.attainment * 100).toFixed(0)} % · gap ${gbp(c.gapGbp.low)}–${gbp(c.gapGbp.high)} · ${c.status} · confidence ${c.confidence}<br>formula: ${esc(c.formula)}<br>assumptions: ${esc(c.assumptions.join("; "))}<br>evidence: ${c.evidence.join(", ")}</span>`)).join("")}</table>
<h2>3. Forward exposure</h2><table>${r.exposures.map((e) => row(e.id, `${esc(e.name)} — p = ${e.probability} (<em>${esc(e.probabilityBasis)}</em>) · ${gbp(e.valueAtRiskGbp.low)}–${gbp(e.valueAtRiskGbp.high)} over ${e.horizonMonths} months<br><span class="small">${esc(e.formula)}</span>`)).join("")}</table>
<h2>4. Value of information</h2><table>${r.voi.map((v) => row(v.interventionId, `<strong>${v.decision.replace(/_/g, " ")}</strong> — ${esc(v.reason)}<br><span class="small">EV ${gbp(v.expectedValueGbp)} · EVPI ${gbp(v.evpiGbp)} · EVSI ${gbp(v.evsiGbp)} · information cost ${gbp(v.informationCostGbp)}</span>`)).join("")}</table>
<h2>5. Allocation and decision</h2><p>${esc(r.decision.question)}</p><table>${r.allocation.lines.map((l) => { const i = r.interventions.find((x) => x.id === l.interventionId)!; return row(l.interventionId, `${l.funded ? "<strong>FUNDED " + gbp(l.allocatedGbp) + "</strong>" : "<strong>BLOCKED</strong>"} — ${esc(i.name)}<br><span class="small">cost ${gbp(i.costGbp)} · effect if it works ${gbp(i.effectIfWorksGbp.low)}–${gbp(i.effectIfWorksGbp.high)} · confidence ${i.confidence} · reversibility ${i.reversibility} · risk-adjusted ${gbp(l.riskAdjustedValueGbp)}${l.blockedBy.length ? "<br>reasons: " + esc(l.blockedBy.join(" | ")) + "<br>required condition: " + esc(l.requiredCondition ?? "") : ""}</span>`); }).join("")}${row("Reserve", gbp(r.allocation.reserveGbp) + " never allocated")}${row("Formula", esc(r.allocation.formula))}${row("Assay verdict", `<strong>${r.assay.verdict}</strong> — ${esc(r.assay.reason)}`)}${row("Governance", `level ${r.decision.governance.level} — ${esc(r.decision.governance.reason)}`)}</table>
<h3>What would change this decision</h3><ul>${r.decision.wouldChangeIf.map((c) => `<li>${esc(c.metric)} ${esc(c.operator)} ${c.threshold}: ${esc(c.why)}</li>`).join("")}</ul>
<h2>6. Pre-registered measurement</h2>${r.plan ? `<table>${row("Plan", `${r.plan.id} v${r.plan.version}${r.plan.supersedes ? " supersedes " + r.plan.supersedes : ""}`)}${row("SHA-256", `<code>${r.plan.sha256}</code>`)}${row("Registered", esc(r.plan.registeredAt))}${row("Primary metric", esc(r.plan.primaryMetric))}${row("Expected", `${gbp(r.plan.expectedGbp.low)} – ${gbp(r.plan.expectedGbp.high)} (point ${gbp(r.plan.expectedPointGbp)})`)}${row("Success rule", esc(r.plan.successRule))}${row("Stopping rule", esc(r.plan.stoppingRule))}</table>` : "<p>Nothing funded: no plan registered.</p>"}
<h2>7. Measurement</h2>${m ? `<table>${row("Status", `<strong>${m.status}</strong> · plan ${m.planStatus} · plan intact ${m.planIntact}`)}${row("Incremental", `${gbp(m.incrementalPointGbp)} (90 % ${gbp(m.incrementalGbp.low)} to ${gbp(m.incrementalGbp.high)}) · P(effect &gt; 0) ${(m.pPositive * 100).toFixed(0)} %`)}${row("Observed vs counterfactual", `${gbp(m.observedGbp)} vs ${gbp(m.counterfactualGbp)}`)}${row("Method", esc(m.method) + " — " + esc(m.methodWhy))}${row("Placebo", `rank ${m.placebo.rank} of ${m.placebo.of} — ${esc(m.placebo.note)}`)}${row("Pre-period fit (RMSPE)", (m.preFitRmspe * 100).toFixed(1) + " %")}${r.outcome ? row("Simulated truth", `${gbp(r.outcome.trueGainGbp)} — ${esc(r.outcome.note)}`) : ""}</table>` : "<p>No measurement in this run.</p>"}
<h2>8. Learning</h2>${r.learning ? `<table>${row(r.learning.id, `expected ${gbp(r.learning.expectedGbp)} · observed ${gbp(r.learning.observedGbp)} · error ${(r.learning.error * 100).toFixed(0)} %<br>${esc(r.learning.calibrationNote)}`)}</table>` : "<p>No learning record.</p>"}
<h2>9. Limitations</h2><ul><li>All property data is simulated; no property system is connected; nothing here is a customer result.</li><li>Benchmarks are placeholders (status BENCHMARK) until documented sources replace them.</li><li>Probabilities of exposure are modelled assumptions, not estimates from data.</li><li>The measurement window is simulated: in practice a 52-week window must elapse.</li></ul>
<h2>Event log</h2><table>${r.events.map((e) => row(`${e.seq} · ${esc(e.at.slice(11, 23))}`, `<span class="tag">${e.state}</span> ${esc(e.type)} — ${esc(e.detail)}`)).join("")}</table>
</body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
}
